package hr.as2.inf.common.exceptions;

import java.util.ListResourceBundle;
/**
 * The infrastructure error codes. The infrastructure code
 * does not use text as the message description. It uses
 * the numbers from this resource bounde.
 * 
 * Infrastructure error codes From 10 To 1999.
 * @version 1.0 
 * @author 	Zdravko Rosko
 */
public class AS2DefaultResourceBundle extends ListResourceBundle {
	private Object[][] _contents = {
	// Reserved From 0 To 10
	// Common From 10 To 100
	{"10","Illegal Access Exception."},
	{"11","Illegal Argument Exception."},
	{"12","Invocation Target Exception"},
	{"13","Other Exception."},
	{"14","No such business service defined."},
	{"15","No such business component defined."},
	{"16","Server error."},
	// Business Logic From 101 To 150 
	{"101","No Data Access Object found."},
	{"102","Business Object not created."},
	// Data Access From 151 To 200
	{"151","Add failed."},	
	{"152","Delete failed."},	
	{"153","System Query failed."},	
	{"154","Can not read Data Access Object Registry for Log Services."},
	{"155","Data Access Object can not be created."},
	{"156","Query Data Access Object can not be created."},
	{"157","Can not read service catalog."},
	{"158","Error while reading services catalog."},
	{"159","Error while reading catalog file fields."},
	{"160","Error while reading services catalog file."},
	{"161","Error during persistenece service connections initialization."},
	{"162","Update failed, affecting more then one row."},
	{"163","Update failed."},
	{"164","Timestamp not sent to server for update."},
	{"165","Timestamp checking failed."},
	{"166","Update timestamp changed since last read."},
	{"167","Data access method not implemented yet."},
	{"168","Timestamp not found in the persistence(DB)."},
	{"169","Unable to auto-generate a key for the give table and column."},
	// Messaging From 201 To 220
	{"201","Invalid Request Model NULL."},
	{"202","Communication timeout."},
	{"203","Invalid Column number."},
	{"204","Exception not handled properly."},
	// Connection From 211 To 300
	{"221", "The directory does not exist."},
	{"222", "The directory is empty."},
	{"223", "The directory list failed."},
	{"224", "Connection from APS is not valid."},
	{"225", "Connection from APS failed to return to pool."},
	{"251", "Error destroying the connection pool."},
	{"252", "No option to create dynamic connection."},
	{"253", "No connections available."},
	{"254", "Error adding connections to the transaction."},
	{"255", "Connection shut down in progress."},
	{"260", "Can not commit JDBC transaction."},
	{"261", "Can not connect JDBC."},
	{"262", "Can not disconnect JDBC."},
	{"263", "Can not rollback JDBC."},
	{"264", "Can not initialize JDBC connection manager."},
	{"265", "Can not create JDBC connection."},
	{"266", "Can not initialize AS400 connection manager."},	
	{"271", "Error checking CICS server statis."},
	{"272", "Can not connect to CICS."},	
	{"273", "Can not disconnect from CICS."},	
	{"274", "Error sending message to CICS."},	
	{"275", "Can not create CICS connection."},	
	{"276", "Can not initialize CICS connection manager."},	
	{"280", "Can not commit MQ transaction."},
	{"281", "Can not connect MQ."},
	{"282", "Can not disconnect MQ."},
	{"283", "Can not rollback MQ."},
	{"284", "Can not initialize MQ connection manager.."},
	{"285", "Can not create MQ connection."},
	{"286", "Could not close MQ queue."},
	{"287", "Could not receive MQ message response."},
	{"288", "Can not create AS400 connection."},
	{"289", "Cannot connect AS400."},
	{"290", "Can not disconnect AS400."},
	{"291", "Can not copy file from AS400, no connection available."},
	{"292", "Can not copy file from AS400, file names not specified."},
	{"293", "File on AS400 does not exist."},
	{"294", "File on AS400 specified is not afile."},
	{"295", "Can not read from AS400 file."},
	{"296", "Can not to the destination file."},
	{"297", "Problem with the destination directory."},
	{"298", "Can not initialize FTP connection manager."},	
	{"299", "Can not create FTP connection."},
	// Services From 301 To 350
	{"301","Invalid Connection Manager Type specified."},
	{"302","Error retrieving connection from transaction."},
	// Rules Service From 351 To 400	
	{"351","Can not initialize Rule Engine."},	
	// Session From 401 To 450
	{"401", "SessionBO.fetch problem."},
	{"402", "SessionBO.add problem."},	
	// Transaction From 451 To 500
	{"451","Transaction has to be rolledbacked."},	
	{"452","No MMTransaction in progress."},
	{"453","Transaction timed out."},
	{"454","Transaction compensation failed."},
	// Transport From 501 To 550
	{"501","Could not find the transport server."},
	{"502","Could not receive results from the transport server."},				
	{"503","Internal Error using HTTP client."},
	{"504","Unable to connect to send using HTTP client."},				
	{"505","Unable to open input stream."},
	{"506","Unable to read a response object from the input stream."},
	{"507","Unable to instantiate the response object."},
	{"508","Unable to open output stream."},
	{"509","Error streaming message object."},
	{"510","Local Transport error."},
	{"511","Server can not read the transaction request."},
	{"512","Transport error: unable to connect to any servers."},
	{"514","RMI server connection error."},
	{"515","EJB server connection error."},
	// Security From 551 To 600
	{"551", "Potrebna prijava u aplikaciju."},
	{"552", "Log out incorrect."},
	{"553", "Already Logged in."},
	{"554", "Invalid password change."},	
	{"555", "Failed to add user."},
	{"556", "Problem updating user session."},
	{"557", "Unable to communicate with the JNDI/LDAP service."},
	{"558", "JNDI/LDAP Naming problem."},
	{"559", "UNKNOWN JNDI/LDAP Security Problem"},
	{"560", "Invalid RACF user id."},
	{"561", "RACF User account is locked."},
	{"562", "Invalid RACF password."},
	{"563", "Korisničko ime je zauzeto."},
	{"564", "Korisnik nema ovlasti za mjenjanje podataka."},
	// TH From 601 To 650
	{"601", "Can not retrieve account name."},
	// Client side From 651 To 800
	{"651", "Unknown error."},
	{"652", "Greška kod kreiranja izvještaja."},
	{"653", "Greška kod prikaza izvještaja."},
	{"654", "Izjveštaj nema podataka."},	
	{"655", "Greska kod kreiranja forme."},
	{"656", "Greška kod otvaranje Excel-a"},
	{"657", "Greška kod kreiranja zaglavlja Excel-a"},
	{"658", "Greška kod punjenja podacima Excel-a"},
	{"659", "Dozvojeno samo čitanje podataka (SELECT * FROM ...)"},
	{"660", "Nije implementirana tražilica."},
	{"661", "Preveliki opseg podataka za prikaz !!!???."},
	{"662", "Ne postoji datoteka u ARHIVI / najprije pregledajte datoteku pritiskom na dugme PRIKAZI iz SPOOLA!!!???."},
	{"663", "Ne postoji SPOOL datoteka !!!???."},
	{"664", "Niste odabrali SPOOL datoteku !!!???."},
	// Test messages From 801 To 900
	{"801", "Form Validation Failed - "},
	// Validation exceptions From 900 To 999
	{"900", "Polje @ je predugo, maksimalna duzina ne smije preci @ znakova."}, //TODO ubaciti ime polja u poruku
	{"901", "Obavezna polja: @."},
	{"902", "Polja @ nisu ispravna."},
	{"1000", "Korisničko ime je zauzeto"},
	{"1001", "Korisničko ime je obevezno"},
	{"1002", "Zaporka je obevezna"},
	{"1003", "Odaberite ime i prezime radnika"},
	{"1004", "Odaberite vrstu korisnika"},
	{"2001", "Odbacivanje neuspjesno, status naloga smije biti samo - prijavljen"},
	{"2002", "Odobravalje neuspjesno, status naloga smije biti - prijavljen ili odbacen"},
	{"2003", "Kontrola naloga neuspjesna, status naloga smije biti samo - odobren"},
	{"2004", "Ovjera naloga neuspjesna, status naloga smije biti samo - zavrsen"},
	{"2005", "Preuzimanje naloga neuspjesno, status naloga smije biti samo - ovjeren"},
	{"2006", "Promjena neukladnosti vise nije moguca"},
	{"2007", "Promjena prijave kvara vise nije moguca"},
	{"2008", "Nesukladnost se vise ne moze brisati"},
	{"2009", "Prijava kavara se vise ne moze brisati"},
	{"2010", "Radni nalog se ne moze brisati"},
	{"2011", "Unosenje uzroka neuspjesno, status nesukladnosti smije biti samo - prijavljena ili uzrok"},
	{"2012", "Unosenje odluke neuspjesno, status nesukladnosti smije biti samo - uzrok ili odluka"},
	{"2013", "Unosenje kontrole neuspjesno, status nesukladnosti smije biti samo - odluka ili zavrsen ili nedovrsen"},
	{"2014", "Unosenje ocjene neuspjesno, status nesukladnosti smije biti samo - zavrsen ili ocjena"},
	{"2015", "Promjena poziva vise nije moguca"},
	{"2016", "Poziv se vise ne moze brisati"},
	{"2017", "Odbacivanje neuspjesno, status poziva smije biti samo - prijavljen"},
	{"2018", "Autorizacija neuspješna, status poziva smije biti - prijavljen ili odbacen"},
	{"2019", "Odobravanje neuspjesno, status poziva mora biti - autoriziran"},
	{"2020", "Datumi pocetak i kraj su neispravni"},
	{"2021", "Zapis vec postoji u bazi"},
	{"2022", "Odaberite radnika za unos"},
	{"2023", "Odbacivanje neuspjesno, status zahtjevnice smije biti samo - prijavljen"},
	{"2024", "Odobravalje neuspjesno, status zahtjevnice smije biti - prijavljen ili odbacen"},
	{"2025", "Promjena zahtjevnice više nije moguća, odobrena ili izdana količina su veće od nule"},
	{"2026", "Odobrena kolicina mora biti jednaka ili manja od trazene kolicine."},
	{"2027", "Izdana kolicina mora biti jednaka ili manja od odobrene kolicine."},
	{"2028", "Izdatnica je vec napravljena."},
	{"2029", "Status mora biti odobren."},
	{"2030", "Brisanje zahtjevnice vise nije moguca"},
	{"2031", "Datum početka neispravan"},
	{"2032", "Datum kraja neispravan"},
	{"2033", "Datum ne smije biti veci od današnjeg."},
	{"2034", "Odaberite tip dogadaja."},
	{"2035", "Odaberite vozilo."},
	{"2036", "Nije dozvoljeno brisanje vozaca. Moguce je promjentiti radno mjesto umjesto brisanja."},
	{"2037", "Neispravan datum rodenja."},
	{"2038", "Ime je obavezno polje."},
	{"2039", "Prezime je obavezno polje."},
	{"2040", "Odaberite status radnika."},
	{"2041", "Neispravan datum zaposlenja."},
	{"2042", "Neispravan datum zadnjeg pregleda."},
	{"2043", "Odaberite sluzbu radnika."},
	{"2044", "Odaberite radno mjesto radnika."},
	{"2045", "Odaberite lokaciju radnika."},
	{"2046", "Neispravan datum izdavanja vozacke dozvole."},
	{"2047", "Neispravan datum isteka vozacke dozvole."},
	{"2048", "Odaberite kategoriju vozacke dozvole za vozaca."},
	{"2049", "Sifarnik se ne smije brisati."},
	{"2050", "Datum povratka na posao nije ispravan, mora biti kasnije od kraja godisnjeg"},
	{"2051", "JMBG nije ispravan"},
	{"2052", "Godina proizodnje ne smije biti veca od trenutne godine."},
	{"2053", "Datum kupnje vozila ne smije biti veći od današnjeg datuma."},
	{"2054", "Datum prodaje vozila ne smije biti veći od današnjeg datuma."},
	{"2055", "Datum registracije vozila ne smije biti veći od današnjeg datuma."},
	{"2056", "Datum tehničkog pregleda vozila ne smije biti veći od današnjeg datuma."},
	{"2057", "Datum početka kredita ne smije biti veći od datuma završetka."},
	{"2058", "Odaberite vrstu radnje."},
	{"2059", "Odaberite vrstu goriva."},
	{"2060", "Unesite stanje kilometraže vozila."},
	{"2061", "Vrijeme izlaza ne smije biti ranije od vremena ulaza."},
	{"2062", "Registarska oznaka ne smije biti unešena ako nije privatni dovoz."},
	{"2063", "Deponij je zatvoren, nije dozvoljen ulaz."},
	{"2064", "Deponiranje dozvoljeno samo za Čistoću d.o.o. Zadar."},
	{"2065", "Deponij ne postoji."},
	{"2066", "Zabranjeno odlaganje odabrane vrste otpada."},
	{"2067", "Zabranjeno odlaganje za unešenog kupca."},
	{"2068", "Odaberite registarsku oznaku vozila."},
	{"2069", "Odaberite putni list."},
	{"2070", "Izmjena putnog lista nije više moguća jer je registriran odlazak vozila iz garaže."},
	{"2071", "Izmjena putnog lista nije više moguća jer je registriran dolazak vozila u garažu."},
	{"2072", "Neispravan datum putnog lista, datum mora biti danasnji ili manji."},
	{"2073", "Putni list je zatvoren, izmjene više nisu moguće."},
	{"2074", "Unos dolaska vozila je nije više moguće."},
	{"2075", "Datum odlaska mora biti veći od datuma ovlaštenja putnog lista."},
	{"2076", "Datum povratka mora biti veći od datuma odlaksa vozila iz garaže."},
	{"2077", "Kilometraža nije ispravna, provjerite stanje kilometraže na vozilu."},
	{"2078", "Unešena kilometraža previše odstupa od trenutnog stanja na vozilu."}, 
	{"2079", "Izabrano vozilo ima otvoren putni list."},
	{"2080", "Vrijeme dolaska mora biti ranije od vremena polaska."},
	{"2081", "Vrijeme polaska mora biti ranije od vremena utovara."},
	{"2082", "Vrijeme utovara mora biti ranije od vremena istovara."},
	{"2083", "Putni list mora biti u statusu dolazak prije unosa kretanja vozila."},
	{"2084", "Neispravan unos stanja brojila, stanje mora biti izmedu garažnog odlaska i dolaska."},
	{"2085", "Zbroj kilometraže, stanje, prazno, puno, prelazi kilometražu povratka u garažu."},
	{"2086", "Postotak popunjenosti neispravan, ne smije biti veći od 100%."},
	{"2087", "Lokacija premještanja kontejnera ne smije biti ista kao i trenutna lokacija."},
	{"2088", "Planirani datum premještanja neispravan, mora biti raniji od datuma premještanja."},
	{"2089", "Broj vozačke je obavezno polje."},
	{"2090", "Neispavna godina kalendara."},
	{"2091", "Neispavan mjesec kalendara."},
	{"2092", "Neispavan unost u polje dani: valjane vrijednosti su N,P,S ili broj"},
	{"2093", "Sva polja su obavezna za unos."},
	{"2094", "Radnik sa istim imenom vec postoji."},
	{"2095", "Vozilo sa istim registarskim tablicama vec postoji."},
	{"2096", "Odaberite ime i prezime vozača."},
	{"2097", "Ime i prezime vozača za privatni dovoz se ne unosi."},
	{"2098", "Kupac se ne unosi."},
	{"2099", "Opis vozila se ne unosi."},
	{"2100", "Vozilo Čistoće se ne unosi."},
	{"2101", "Vozač Čistoće se ne unosi."},
	{"2102", "Registarska oznaka za privatni dovoz je obavezna."},
	{"2103", "Ime vozača za privatni dovoz je obavezno."},
	{"2104", "Nazv kupca je obavezan kad se unosi evidencija za trvtku."},
	{"2105", "Vrsta otpada je obavezna."},
	{"2106", "Jedinica mjere je obavezna."},
	{"2107", "Količina je obavezna."},
	{"2108", "Vrsta dodatne prisutnosti već je unešena."},
	{"2109", "Radnik je u na godišnjem, bolovanju ili odsutan u unešenom periodu."},
	{"2110", "Kilometraža je neispravna, mora biti veća od odlaska i manja od dolaska."},
	{"2111", "Nisu pronađeni nikakvi podaci za ispis."},
	{"2112", "Putni list se nemože više brisati."},
	{"2113", "Autorizacija neuspješna, poziv mora biti obilježen kao narudžba."},
	{"2114", "Vrsta usluge je obavezno polje kod autorizacije narudžbe."},
	{"2115", "Odaberite ili kupca sa ugovorom ili upišite broj narudžbe."},
	{"2116", "Godina i mjesec početka i kraja moraju biti isti. Za prelaz u drugi mjesec napravite dva unosa."},
	{"2117", "Datum početka i kraja moraju biti od 1-15 u mjesecu. Za prelaz u drugi dio mjeseca napravite dva unosa."},
	{"2118", "Datum početka i kraja moraju biti od 15-31 u mjesecu. Za prelaz u novi mjesec napravite dva unosa."},
	{"2119", "Neispravan unos mjeseca, mora biti broj."},
	{"2120", "Neispravan unos godine, mora biti broj."},
	{"2121", "Objekt je obavezno polje za ugovorenog kupca."},
	{"2122", "Podaci su ušli u obračun i nemogu se više mjenjati."},
	{"2123", "Datum početka mora biti poslije početka radnog naloga."},
	{"2124", "Datum kraja mora biti prije kraja radnog naloga."},
	{"2125", "Vrijeme od-do neispravno."},
	{"2126", "Datumi od-do moraju biti na isti dan."},
	{"2127", "Ne postoji kalendar za unešenu godinu - potreban unos."},
	{"2128", "Odaberite odsutnost tipa godišnji odmor."},
	{"2129", "Datum pražnjenja kontejnera mora biti manji ili jednak od današnjeg datuma."},
	{"2130", "Unesite samo jednu destinaciju pražnjenja (deponij, kupac ili ostalo)."},
	{"2131", "Težina je obavezno polje."},
	{"2132", "Nosivost u kilogramima je obavezno polje."},
	{"2133", "Nosivost u metrima kubnim je obavezno polje."},
	{"2134", "Kontejner sa istim identifikatorom već postoji."},
	{"2135", "Naziv kupca je obavezno polje."},
	{"2136", "Izmjena nije dozvoljna, brisanje je dozvoljeno."},
	{"2137", "Podaci za godinu, mjesec, vrstu vec postoje."},
	{"2138", "Unesite trenutno stanje kilometraže."},
	{"2139", "Datum periodičkog pregleda ne smije biti veći od današnjeg datuma."},
	{"2140", "Primjedbu unosi ili briše samo direktor."},
	{"2141", "Šifra kupca se ne unosi za neugovorene kupce."},
	{"2142", "Izaberite vrstu izvještaja."},
	{"2143", "Težina nesmije biti manja od težine vozila."},
	{"2144", "Datum slijedećeg pregleda je neispravan."},
	{"2145", "Izaberite vrstu podataka koje želite arhivirati!"},
	{"2146", "Izaberite vrstu podataka koje želite povratiti iz arhive!"},
	{"2147", "Unesite naziv."},
	{"2148", "Izaberite komponentu."},
	{"2149", "Već postoje ovlasti za izabranu komponentu."},
	{"2150", "Komitent nema dospjelih obveza za navedeni datum, stoga se ne prikazuje ročnost."},
	{"2151", "Unesite samo matični broj komitenta ukoliko se podaci ne odnose na noćnu obradu."},
	{"2152", "Odabrani dan nije Nedjelja po kalendaru postavljenom u sustavu."},
	{"2153", "Ljetni mjeseci su samo 6,7 ili 8."},
	{"2154", "Kada se želi prikazati ročnost za više klijenata odvojenih zarezom, moraju se odabrati PODACI NOĆNE OBRADE "},
	{"10000", "Unesite raspon partija, naziv ili matični broj!"},
	{"10001", "Unesite zadnji dan u mjesecu!"},
	{"10002", "Grafički prikaz je moguć samo za jednu partiju, odaberite partiju sa prikaza ispod !"},
	{"10003", "Unesite prvi dan u mjesecu!"},
	{"10004", "Ne postoji obrada za ponavljanje sa odabranim datumima!"},
	{"10005", "Unešeni datumi se preklapaju sa postojećim obradama u sustavu!"},
	{"10006", "Unesite neke od podataka za pretraživanje!"},
	{"10007", "Neispravan broj partije!"},
	{"10008", "Neispravan matični broj!"},
	{"10009", "Unesite datum jednak ili manji od današnjeg!"},
	{"10010", "Sačekajte nekoliko minuta i probajte ponovno, drugi korisnik je pokrenuo obradu!"},
	{"10011", "Ne postoji obrada opomena za ponavljanje sa odabranim datumom!"},
	{"10012", "Unešeni datum se preklapa sa postojećim obradama opomena u sustavu!"},	
	{"10013", "Neispravan datum od, datum mora biti današnji ili manji."},	
	{"10014", "Datum od mora biti manji od datuma do."},
	{"10015", "Iznos smije biti cijeli broj (-ili+)"},
	{"10016", "Iznos od nemije biti veći od iznosa do"},
	{"10017", "Izaberite vrstu izvještaja sa liste (niste izabrali vrstu izvještaja)"},
	{"10018", "Partija ne postoji u sustavu."},
	{"10019", "Odaberite vrstu kreditnog programa."},
	{"11001", "Unesite sve podatke (jamstveni kapital, cijenu dionice i broj dionica."},
	{"11002", "Partija je već povezana s kolateralom."},
	{"11003", "Unesite naziv imovine."},
	{"11004", "Unesite kategoriju imovine."},
	{"11005", "Neispravan matični broj klijenta."},
	{"11006", "Neispravan broj partije."},
	{"11007", "Unesite naziv zgrade."},
	{"11008", "Unesite sifru zgrade."},
	{"11009", "Unesite naziv lokacije."},
	{"11010", "Kolateral nije unešen u bazu. Prvo spremite kolateral a onda dodajte policu osiguranja."},
	{"11011", "Kolateral nije unešen u bazu. Prvo spremite kolateral a onda dodajte teret (partiju)."},
	{"11012", "Nije unešen niti jedan plan poslovanja za klijenta."},
	{"11013", "Zahtjev nije dupliciran (ne postoji u bazi podataka)."},
	{"11014", "Početak je nove kalendarske godine. Unesite datume u istoj godini."},
	{"11015", "Datumi nisu u nizu."},
	{"11016", "Podatke povezanih osoba koji se nalaze u BSA sustavu nije moguće mijenjati u ovoj aplikaciji."},
	{"11017", "Neispravan OIB!"},
	//pranje novca
	{"12000", "Potrebno je unijeti broj partije."},
	{"12001", "Broj partije ne odgovara klijentu."},
	{"12002", "Neispravan unos države korespodencije."},
	{"12003", "Neispravan unos države rođenja."},
	{"12004", "Neispravan unos države izdavatelja osobne iskaznice."},
	{"12005", "Neispravan unos države izdavatelja osobne putovnice."},
	{"12006", "Neispravan unos države prebivališta."},
	{"12007", "Potreban unos podataka osobne iskaznice ili putovnice."},
	{"12008", "Potrebno je izabrati različite osobe. Osoba ne može biti vezana sama na sebe."},
	{"12009", "Pravna osoba za koju se ispunjava upitnik nemože se povezivati sama sa sobom."},
	{"12010", "Nova obrada treba krenuti od datuma većeg nego zadnja obrada!"},
	{"12011", "Odaberite crnu listu!"},
	//bonitet obrtnika
	{"12500", "Potrebno je unijeti (godinu, ukupne primitke, ukupne izdatke)."},
	{"12501", "Podaci za unešenu godine već postoje, promjenite godinu na koju se odnose podaci."},
	//helpdesk
	{"12800", "Komentari se nemogu mijenjati niti brisati."},
	{"12801", "Procjena rizika za unešeni broj zahtjeva već postoji."},
	{"12802", "Odaberite vrstu."},
	{"12803", "Unesite godinu."},
	{"12804", "Korisnik nema ovlasti za mjenjanje podataka."},
	{"12805", "Odaberite tip entiteta i vrstu klijenta."},
	{"12806", "Zatvaranje zahtjeva može napraviti samo osoba koja je otvorila zahtjev i napravila korisnički test."},
	{"12807", "Za zatvaranje zahtjeva potrebno je koristiti izbornik -promjeni status-."},
	{"12808", "Obavezna polja za unos us naziv i osoba prijave."},
	{"12809", "Obavezna polja za unos us naziv, osoba prijave i odgovorana osoba."},
	//isms
	{"13000", "Odaberite organizacijsku jedinicu sa liste."},
	//isms - or
	{"13500", "Naziv događaja nije unešen."},
	{"13501", "Kategorija događaja nije unešena ili nije odabrana druga razina po Basel II."},
	{"13502", "Uzrok događaja nije unešen."},
	{"13503", "Naziv gubitka nije unešen."},
	{"13504", "Kategorija gubitka nije unešena."},
	//zahtjevi
    {"14000", "Unesite obrazloženje odluke."},
    {"14001", "Ne postoji niti jedan poslovni plan u bazi."},
    {"14002", "Unesite cijeli broj."},
    {"14003", "Podaci za unešenu valutu već postoje u sustavu."},
    {"14004", "Datum dospjeća ne smije biti veći za godinu dana od datuma specifikacije, banka otkupljuje nedospjela potraživanja na rok do 1 godine."},
    {"14005", "Datum dospijća ne smije biti raniji od datuma specifikacije."},
    {"14006", "Unesite OIB ili matični broj ili JMBG."},
    {"14007", "Unesite samo jedan podataka (JMBG ili matični broj)."},
    {"14008", "Klijent nema zaduženja u Banci. Ukoliko je klijent fizička osoba, unesite zadnji dan mjeseca u polje datum stanja."},
    {"14009", "Izmjena tj. izračun rejtinga se može raditi samo za zadnji datum."},
    //rizici
    {"14500", "Promjena ocjene i vrijednosti pokazatelja u isto vrijme nije dozvoljena."},
    {"14501", "Broj zahtjeva koji je unešen ne postoji u bazi podataka za pravnu osobu."},
    {"14502", "Mišljenje nije duplicirano (ne postoji u bazi podataka)."},
    {"14503", "Brisanje pokazatelja nije dozvoljeno."},
    //čekovi
    {"15000", "Nepotpuni podaci."},
    {"15001", "Ne postoji partija za zadani jmbg."},
    {"15002", "Ne postoji partija za zadani oib."},
    {"15003", "Ne postoji neiskorišteni serijski broj čeka za zadanu partiju."},
    {"15004", "Dupli unos istog serijskog broja"},
    //naplata
    {"15500", "Klijent postoji u bazi podataka."},
    {"15501", "Neispravan format polja \"Datum uplate\". Ispravan format je \"DD.MM.GGGG\"."},
    {"15502", "Neispravan format polja \"Datum budućeg kontakta\". Ispravan format je \"DD.MM.GGGG\"."},
    {"15503", "Neispravan format polja \"Datum podnošenja / izmjene prijedloga za ovrhu\". Ispravan format je \"DD.MM.GGGG\"."},
    {"15504", "Neispravan format polja \"Datum potvrde primitka JB\". Ispravan format je \"DD.MM.GGGG\"."},
    {"15505", "Neispravan format polja \"Datum pravomoćnosti\". Ispravan format je \"DD.MM.GGGG\"."},
    {"15506", "Neispravan format polja \"Datum slanja na FINA-u\". Ispravan format je \"DD.MM.GGGG\"."},
    {"15507", "Neispravan format polja \"Datum predaje spisa\". Ispravan format je \"DD.MM.GGGG\"."},
    {"15508", "Nisu popunjena sva obavezna polja."},
    {"15509", "Neispravan format datuma."},
    {"15510", "Datum budućeg kontakta mora biti unutar 90 dana u odnosu na današnji dan."},
    //ostalo
    {"16000", "Unesite datum za koji želite generirati temeljnicu."},
    {"16001", "Neuspješno povezivanje sa poslužiteljem."},
    {"16002", "Neispravan korisnički identitet."},
    {"16003", "Neispravna zaporka."},
    {"16004", "Neispravan format datuma."},
    {"16005", "Neispravan format iznosa."},
    {"16006", "Nije omogućeno brisanje više redaka."},
    //kalkulatori
    {"16101", "Unesite iznos kredita."},
    {"16102", "Unesite kamatnu stopu."},
    {"16103", "Unesite broj godina."},
    {"16104", "Broj godina, broj rata počeka ili šifra protuvalute mora biti numrički."},
	};
protected Object[][] getContents() {
	return _contents;
}
}
